apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipl-deployment
  labels:
    app: ipl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipl
  template:
    metadata:
      labels:
        app: ipl
    spec:
      containers:
        - name: ipl
          image: ipl:0.0.1
          env:
            - name: KAFKA_HOST
              value: "host.docker.internal:9094"
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: MYSQL_URL
              value: "jdbc:mysql://host.docker.internal:1000/ipl"
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ipl-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ipl-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: ipl-service
spec:
  selector:
    app: ipl
  type: NodePort
  ports:
    - port: 90
      targetPort: 9000
      nodePort: 30005