spring:
  application:
    name: ipl-api-gateway
  cloud:
    gateway:
      routes:
        - id: insert-match-data
          uri: ${MATCH_API_URI:http://localhost:9000}
          predicates:
            - Path=/api/matches/insert
        - id: get-matches-by-player
          uri: ${MATCH_API_URI:http://localhost:9000}
          predicates:
            - Path=/api/matches/player/**
        - id: get-cumulative-score
          uri: ${MATCH_API_URI:http://localhost:9000}
          predicates:
            - Path=/api/matches/cumulative-score
        - id: get-scores-by-date
          uri: ${MATCH_API_URI:http://localhost:9000}
          predicates:
            - Path=/api/matches/score
        - id: get-top-batsmen
          uri: ${MATCH_API_URI:http://localhost:9000}
          predicates:
            - Path=/api/matches/topbatsmen
#jwt:
#  secret:
#    endpoint: http://your-config-service/jwt-secret
server:
  port: 7000
